import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const Aeonik = localFont({
  src: [
    {
      path: '../app/assets/fonts/Aeonik-font-download/Aeonik-Air.otf',
      weight: '600'
    },
    {
      path: '../app/assets/fonts/Aeonik-font-download/Aeonik-Black.otf',
      weight: '800'
    },
    {
      path: '../app/assets/fonts/Aeonik-font-download/Aeonik-Bold.otf',
      weight: '700'
    },
    {
      path: '../app/assets/fonts/Aeonik-font-download/Aeonik-Light.otf',
      weight: '100'
    },
    {
      path: '../app/assets/fonts/Aeonik-font-download/Aeonik-Medium.otf',
      weight: '500'
    },
    {
      path: '../app/assets/fonts/Aeonik-font-download/Aeonik-Regular.otf',
      weight: '400'
    },
    {
      path: '../app/assets/fonts/Aeonik-font-download/Aeonik-Thin.otf',
      weight: '200'
    },
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Aeonik.className}>{children}</body>
    </html>
  );
}
